### ISSUE TITLE
MySQL_extend_eanprod_xx_XX.sql

### ISSUE THREAD

**Issue by Matt007** [ExpediaInc/ean-pc-dbscripts#7]
Line 313 is missing a ";" at the end of the line resulting in a failed sql import.
Adding the ";" fixes this :-)

Currently (before replacing the language) it looks like this:

DROP TABLE IF EXISTS activepropertybusinessmodel_es_es
-> needs to be:
DROP TABLE IF EXISTS activepropertybusinessmodel_es_es;

**Comment by jonarce** [comment]
I fix it directly on the master, thanks for noticing !
